Models/ErrorViewModel.cs
namespace MeasuringInstruments.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

public class User
{
    public int Id { get; set; }

    [Required]
    [MaxLength(15)]
    public string FirstName { get; set; }

    [Required]
    [MaxLength(15)]
    public string LastName { get; set; }

    [Required]
    [DataType(DataType.PhoneNumber, ErrorMessage ="Siz telifon raqamingizni kiritmadingiz")]
    public string PhoneNumber { get; set; }

    [Required]
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; }

    [Required]
    [MaxLength(15)]
    public string Login { get; set; }

    [Required]
    [DataType(DataType.Password)]
    [MaxLength(10)]
    [Range(5, 10, ErrorMessage ="Siz kiritgan parol 5 ta simvoldan 10 ta simvol oralig'ida bo'lishi kerak!")]
    public string Password { get; set; }

    [Required]
    [DataType(DataType.Password)]
    [MaxLength(10)]
    [Range(5, 10, ErrorMessage ="Siz kiritgan parol 5 ta simvoldan 10 ta simvol oralig'ida bo'lishi kerak!")]
    [Compare("Password", ErrorMessage ="Parolingiz to'g'ri kelmadi...")]
    public string PasswordConfirm { get; set; }
}

Controllers/AbbController.cs
using Microsoft.AspNetCore.Mvc;

namespace MeasuringInstruments.Controllers;

public class AbbController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;


namespace MeasuringInstruments.Controllers;

public class AuthController : Controller
{
    private readonly DataContext dbContext;

    public AuthController(DataContext dataContext)
    {
        this.dbContext = dataContext;
    }

    [HttpGet]
    [Route("[controller]/[action]")]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    [Route("[controller]/[action]")]
     public IActionResult SendRegister(User user)
    {
        
            dbContext.Users.Add(user);
            dbContext.SaveChanges();

       
        List<Claim> claims = new List<Claim>()
        {
            new Claim(ClaimTypes.NameIdentifier, user.Email),
            new Claim("OtherProperties", "Example Role")
        };

        ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        AuthenticationProperties properties = new AuthenticationProperties()
        {
            AllowRefresh = true,
            IsPersistent = true
        };
        
        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);

        return RedirectToAction("Index","User");
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    [Route("[controller]/[action]")]
     public IActionResult SendLogin(User odam)
    {
        var user=dbContext.Users.FirstOrDefault(u=>u.Email == odam.Email && u.Password == odam.Password);

        

        List<Claim> claims = new List<Claim>()
        {
            new Claim(ClaimTypes.Email, odam.Email),
            new Claim("FirstName", user.FirstName ),
            new Claim("OtherProperties", "Example Role")
        };

        ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        AuthenticationProperties properties = new AuthenticationProperties()
        {
            AllowRefresh = true,
            IsPersistent = true
        };
        
        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);


        return RedirectToAction("Index", "User");

    }

      public IActionResult Logout()
      {
        HttpContext.SignOutAsync();
        return RedirectToAction("Index", "Home");
      }
}

Controllers/DeviceController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace MeasuringInstruments.Controllers;

public class DeviceController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MeasuringInstruments.Models;

namespace MeasuringInstruments.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MeasuringInstruments.Conntrollers;

[Authorize]
[Route("[controller]")]

public class UserController : Controller
{
    private readonly DataContext dbContext;

    public UserController(DataContext dataContext)
    {
        this.dbContext = dataContext;
    }

    [Route("[action]")]
    public IActionResult Index()
    {
        List<User> users = new List<User>();
        users = dbContext.Users.ToList();

        return View(users);
    }

    [HttpGet]
    [Route("[action]")]
    public IActionResult CreateUser()
    {
        return View();
    }

    [HttpPost]
    [Route("[action]")]
    public IActionResult Store(User user)
    {
        dbContext.Users.Add(user);
        dbContext.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("[action]/{id}")]
    public IActionResult Edit(int id)
    {
        var user = dbContext.Users.Find(id);

        return View(user);
    }

    [HttpPost]
    [Route("[action]/{id}")]
    public IActionResult Update(int id, User newuser)
    {
        var olduser = dbContext.Users.Find(id);

        olduser.FirstName = newuser.FirstName;
        olduser.LastName = newuser.LastName;
        olduser.PhoneNumber = newuser.PhoneNumber;
        olduser.Email = newuser.Email;
        olduser.Login = newuser.Login;
        olduser.Password = newuser.Password;
        olduser.PasswordConfirm = newuser.PasswordConfirm;

        dbContext.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("[action]/{id}")]
    public IActionResult Delete(int id)
    {
        var user = dbContext.Users.Find(id);
        dbContext.Users.Remove(user);
        dbContext.SaveChanges();
        
        return RedirectToAction("Index");
    }
}

Views/Abb/Index.cshtml
<h1>shuxrat</h1>

Views/Device/Index.cshtml
<h1>shuxrat</h1>

<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/images/flowmeter.jpg" class="d-block w-100" alt="..." width="300" height="500">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color: crimson;">Eng so'ngi ma'lumotlar</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="~/images/pressure.jpg" class="d-block w-100" alt="..." width="300" height="500">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color: crimson;">O'zbek tilida</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="~/images/elecflowmeter.jpg" class="d-block w-100" alt="..." width="300" height="500">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color: crimson;">Barchasi bizda</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/Auth_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeasuringInstruments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeasuringInstruments.styles.css" asp-append-version="true" />
</head>
<body style="background-color: chartreuse">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MeasuringInstruments</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MeasuringInstruments - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeasuringInstruments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeasuringInstruments.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://kit.fontawesome.com/a35a4d318e.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MeasuringInstruments</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="CreateUser">User Input</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User Table</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Device" asp-action="Index">Asosiy</a>
                        </li>
                         
                    </ul>
                    <ul class="navbar-nav">
                            @if(User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">@User.Claims.FirstOrDefault(x=>x.Type == System.Security.Claims.ClaimTypes.Email).Value</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Exit<i class="fa-sharp fa-solid fa-right-to-bracket"></i></a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Registrition</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                            }
                            
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MeasuringInstruments - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/CreateUser.cshtml
@model User;

@{
    ViewData["Title"]="Add user";
}

<div class="col-6">
    <form asp-controller="User" asp-action="Store" method="post">
        <div class="mb-3">
            <label for="FirstName">Ismingiz:</label>
            <input type="text" name="FirstName" class="form-control">
        </div>
        <div class="mb-3">
            <label for="LastName">Familiyangiz:</label>
            <input type="text" name="LastName" class="form-control">
        </div>
        <div class="mb-3">
            <label for="PhoneNumber">Telifon raqamingiz:</label>
            <input type="number" name="PhoneNumber" class="form-control">
        </div>
        <div class="mb-3">
            <label for="Email">Elektron pochtangiz:</label>
            <input type="email" name="Email" class="form-control">
        </div>
        <div class="mb-3">
            <label for="Login">Login:</label>
            <input type="text" name="Login" class="form-control">
        </div>
        <div class="mb-3">
            <label for="Password">Parolingiz:</label>
            <input type="number" name="Password" class="form-control">
        </div>
        <div class="mb-3">
            <label for="PasswordConfirm">Parolingizni qayta kiriting:</label>
            <input type="number" name="PasswordConfirm" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">добавить</button>
    </form>
</div>

Views/User/Edit.cshtml
@model User;

@{
    ViewData["Title"]="Edit user";
}

<div class="col-6">
    <form asp-controller="User" asp-action="Update" asp-route-id="@Model.Id" method="post">
       <div class="mb-3">
            <label for="FirstName">Ismingiz:</label>
            <input type="text" name="FirstName" class="form-control" value="@Model.FirstName">
        </div>
        <div class="mb-3">
            <label for="LastName">Familiyangiz:</label>
            <input type="text" name="LastName" class="form-control" value="@Model.LastName">
        </div>
        <div class="mb-3">
            <label for="PhoneNumber">Telifon raqamingiz:</label>
            <input type="number" name="PhoneNumber" class="form-control" value="@Model.PhoneNumber">
        </div>
        <div class="mb-3">
            <label for="Email">Elektron pochtangiz:</label>
            <input type="email" name="Email" class="form-control" value="@Model.Email">
        </div>
        <div class="mb-3">
            <label for="Login">Login:</label>
            <input type="text" name="Login" class="form-control" value="@Model.Login">
        </div>
        <div class="mb-3">
            <label for="Password">Parolingiz:</label>
            <input type="password" name="Password" class="form-control" value="@Model.Password">
        </div>
        <div class="mb-3">
            <label for="PasswordConfirm">Parolingizni qayta kiriting:</label>
            <input type="password" name="PasswordConfirm" class="form-control" value="@Model.PasswordConfirm">
        </div>
        <button type="submit" class="btn btn-success">добавить</button>
    </form>
</div>

Views/User/Index.cshtml
@model List<User>

    @{
        ViewData["Title"]="Table user";
    }

<form action="">
    <table class="table">
    <tr>
        <th>Id</th>
        <th>FirstName</th>
        <th>LastName</th>
        <th>PhoneNumber</th>
        <th>Email</th>
        <th>Login</th>
        <th>Password</th>
        <th>PasswordConfirm</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach(var user in Model)
    {
        <tr>
            <td>@user.Id</td>
            <td>@user.FirstName</td>
             <td>@user.LastName</td>
            <td>@user.PhoneNumber</td>
            <td>@user.Email</td>
            <td>@user.Login</td>
            <td>@user.Password</td>
            <td>@user.PasswordConfirm</td>
            <td><a asp-controller="User" asp-action="Edit" asp-route-id="@user.Id">Изминить</a></td>
            <td><a asp-controller="User" asp-action="Delete" asp-route-id="@user.Id">Удалить</a></td>
        </tr>
    }
    </table>

    <button class="btn btn-outline-danger"><a asp-controller="User" asp-action="CreateUser">Create User</a></button>
</form>